select registro.idRegistro,registro.usuarioRegistro, registro.estadoRegistro,registro.fechaRegistro,plantas.nameplanta, transportador.tipoTransportador,bandaTransportadora.resistenciaRoturaLonaTransportadora,bandaTransportadora.noLonasBandaTransportadora,bandaTransportadora.anchoBandaTransportadora,bandaTransportadora.espesorCubiertaInferiorTransportadora,bandaTransportadora.espesorCubiertaSuperiorTransportadora,bandaTransportadora.espesorTotalBandaTransportadora,bandaTransportadora.longitudSinfinBandaHorizontal, count(transportador.idTransportador) as 'Cantidad Transportadores'

from registro
join plantas on registro.codplanta=plantas.codplanta
join transportador on transportador.idTransportador=registro.idTransportador
join bandaTransportadora on registro.idRegistro=bandaTransportadora.idRegistro
where transportador.tipoTransportador='B.T'

group by registro.usuarioRegistro,registro.idRegistro,registro.estadoRegistro,registro.fechaRegistro, plantas.nameplanta, transportador.tipoTransportador,
transportador.tipoTransportador,bandaTransportadora.resistenciaRoturaLonaTransportadora,bandaTransportadora.noLonasBandaTransportadora,bandaTransportadora.anchoBandaTransportadora,bandaTransportadora.espesorCubiertaInferiorTransportadora,bandaTransportadora.espesorCubiertaSuperiorTransportadora,bandaTransportadora.espesorTotalBandaTransportadora,bandaTransportadora.longitudSinfinBandaHorizontal